//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

public class Guru {
    private String NamaGuru;
    private int NIP;
    private int NUPTK;
    private String Pendidikan;
    private int Kontak;

    public Guru() {
    }

    public String getNamaGuru() {
        return this.NamaGuru;
    }

    public void setNamaGuru(String NamaGuru) {
        this.NamaGuru = NamaGuru;
    }

    public int getNIP() {
        return this.NIP;
    }

    public void setNIP(int NIP) {
        this.NIP = NIP;
    }

    public int getNUPTK() {
        return this.NUPTK;
    }

    public void setNUPTK(int NUPTK) {
        this.NUPTK = NUPTK;
    }

    public String getPendidikan() {
        return this.Pendidikan;
    }

    public void setPendidikan(String Pendidikan) {
        this.Pendidikan = Pendidikan;
    }

    public int getKontak() {
        return this.Kontak;
    }

    public void setKontak(int Kontak) {
        this.Kontak = Kontak;
    }
}
